### ISSUE TITLE
Update core-api

### ISSUE THREAD

**Issue by kalkins** [sparkfun/arduino-mbed-bridge#4]
The commit used for the `core-api` submodule is over a year old, and there have been many updates in the meantime.

For example, https://github.com/arduino/ArduinoCore-API/pull/118 is only four commits after the one that is currently used, and it fixes a bug that made `pgm_read_ptr` unusable, breaking several libraries. This came up in https://github.com/sparkfun/Arduino_Apollo3/issues/417.

I know that we can't just jump to the newest commit, there are breaking changes to consider, but can we at least try to get to version 1.1.0?

**Comment by Wenn0101** [comment]
Forgot to close this issue.

This was fixed with commit [c7a1dcad2a6e2d37253b0a12089550b470bdb0f5](https://github.com/sparkfun/arduino-mbed-bridge/commit/c7a1dcad2a6e2d37253b0a12089550b470bdb0f5)
